### ISSUE TITLE
Process Instance Migration: Backend and Frontend Changes to execute a process migration

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#1671] opened 2024-06-04 17:39 UTC
Placeholder for future sprint - estimation to be determined, I just put a number in here to help guide expectations.  Add some tools to the UI and back-end that will allow you to migrate a process instance to an updated model.  Will need to check if the migration is possible, which will require that the process instance is in a state where the changes are "up stream" or not reached yet.

**Comment by jasquat** [comment] 2024-07-11 18:09
This has been deployed to qa5 for testing.

**Comment by madhurrya** [comment] 2024-07-12 05:24
So if there are 100 instances of a model and if they want to update that model and migrate all the instances, they will have to manually suspend and migrate them one by one for all the 100. Is that how they want to do it?

**Comment by madhurrya** [comment] 2024-07-12 12:07
Noticed these during my testing today.
https://github.com/sartography/spiff-arena/issues/1907
https://github.com/sartography/spiff-arena/issues/1908
https://github.com/sartography/spiff-arena/issues/1909
https://github.com/sartography/spiff-arena/issues/1910

**Comment by madhurrya** [comment] 2024-07-12 15:29
@burnettk @jasquat When a message related task/event is active, if we change the Message of that and migrate, there'll be 2 messages for that. The one already created with the old message and the one that got created after the message update. 
Is that something we need to worry about?

For example
https://timetracking.spiffworkflow.org/i/6258

![Image](https://github.com/user-attachments/assets/007d670b-8259-4339-9460-619351b679cf)

**Comment by jasquat** [comment] 2024-07-12 16:06
That doesn't seem ideal but also doesn't seem wrong. Maybe the correct solution is to allow users to manually disable message instances and they will need to be careful about migrating such things.

**Comment by madhurrya** [comment] 2024-07-15 11:30
> So if there are 100 instances of a model and if they want to update that model and migrate all the instances, they will have to manually suspend and migrate them one by one for all the 100. Is that how they want to do it?

@burnettk any thoughts on this?

**Comment by madhurrya** [comment] 2024-07-15 11:32
If we add/remove a Signal boundary event to the current active task, it won't allow us to migrate that instance. Is that some thing we need to worry about?


![Image](https://github.com/user-attachments/assets/a863a41d-fd31-483f-be6e-493ea00ca6da)



![Image](https://github.com/user-attachments/assets/f88b036a-ea94-4e34-8784-5f4965da1826)

**Comment by madhurrya** [comment] 2024-07-15 13:13
Tested migration at unit test level for these. Please let me know if I have missed anything.

Manual Task
User Task
Service Task
Script Task
Business Rule Task
Send Task
Receive Task
Exclusive Gateway
Parallel Gateway
Inclusive Gateway

Call Activity
Sub process Collapsed
Sub process Expanded

Timers

Data input/output
Data object

Guest user task

Multi Instance (Loop cardinality, Input collection)
Loop

Escalation End Event
Escalation Intermidate Throw Event
Escalation Boundary Event
Escalation Boundary Event (non-interrupting)
Error End Event
Error Boundary Event
Message End Event
Message Intermediate Catch Event
Message Intermediate Throw Event
Message Boundary Event
Conditional Boundary Event
Signal Boundary Event
Timer Intermediate Catch Event
Timer Boundary Event

Lanes

**Comment by madhurrya** [comment] 2024-07-15 13:15
Issues found today

https://github.com/sartography/spiff-arena/issues/1919
https://github.com/sartography/spiff-arena/issues/1920
https://github.com/sartography/spiff-arena/issues/1922

**Comment by madhurrya** [comment] 2024-07-16 04:07
@burnettk @jasquat is there anything to test in data stores related to migration?

**Comment by madhurrya** [comment] 2024-07-16 06:34
@burnettk @jasquat when we go to the migration page, it might be better to update the bread crumb to show that you are in the migration page.


![Image](https://github.com/user-attachments/assets/67f9d788-46e4-443f-a4ae-7a00954217e5)

**Comment by madhurrya** [comment] 2024-07-16 06:36
Issues found today
https://github.com/sartography/spiff-arena/issues/1928

This might be related to the migration updates, but not sure. It could be due to some other recent code change as well.
https://github.com/sartography/spiff-arena/issues/1927

**Comment by burnettk** [comment] 2024-07-17 00:07
added "Migrate" to the breadcrumb. that isn't deployed anywhere yet.

regarding having to suspend and migrate 100 process instances individually, yes, that is understand and this is definitely an area to consider as a future enhancement. we tried to build the simplest thing that could possibly work, but definitely had this potential future use case in mind.

**Comment by madhurrya** [comment] 2024-07-18 03:21
> If we add/remove a Signal boundary event to the current active task, it won't allow us to migrate that instance. Is that some thing we need to worry about?
> 
> ![Image](https://private-user-images.githubusercontent.com/110527567/348689045-a863a41d-fd31-483f-be6e-493ea00ca6da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzE2NzMsIm5iZiI6MTcyMTI3MTM3MywicGF0aCI6Ii8xMTA1Mjc1NjcvMzQ4Njg5MDQ1LWE4NjNhNDFkLWZkMzEtNDgzZi1iZTZlLTQ5M2VhMDBjYTZkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMjU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjc4MGE1NWVkYmY0ZjgyMjA1NmY4YThlZDk5ZGMzZTJhNjJkYzlmMTQxNTEyYTJjMjQyOTQ0MWQzMGI1NzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_cu-Zfu_jZVuBLwN7fByuV4JVp2-I_L4mHiM8hqb6k)
> 
> ![Image](https://private-user-images.githubusercontent.com/110527567/348689151-f88b036a-ea94-4e34-8784-5f4965da1826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzE2NzMsIm5iZiI6MTcyMTI3MTM3MywicGF0aCI6Ii8xMTA1Mjc1NjcvMzQ4Njg5MTUxLWY4OGIwMzZhLWVhOTQtNGUzNC04Nzg0LTVmNDk2NWRhMTgyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwMjU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWYzODk5YzFiN2Y1ODllMDMxNTM0YjgxY2JkMmU5NTc5YmI4ZjI1YzdlMTAwNGNhYmY0NTg3MGQyOGIzOWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QK4D0c7KIg_FzJoXmkOFpv7hRNVSFbLNfq_MO_02NyQ)

@burnettk I guess we are going to leave this as it is now?

**Comment by madhurrya** [comment] 2024-07-18 03:23
@burnettk @jasquat when a user loops back to a task, it doesn't allow me to change it and migrate it, I think because it was already completed once in the previous iteration. I assume that's how it is expected to work.
![image](https://github.com/user-attachments/assets/ca7beb18-4e37-492b-bb38-953b0ff1b05d)

**Comment by madhurrya** [comment] 2024-07-18 06:59
Noticed this issue today
https://github.com/sartography/spiff-arena/issues/1945

**Comment by essweine** [comment] 2024-07-18 18:01
Yes, both are expected.

**Comment by madhurrya** [comment] 2024-07-22 07:12
Noticed this issue today
https://github.com/sartography/spiff-arena/issues/1961

**Comment by madhurrya** [comment] 2024-07-22 10:01
@burnettk While a Guest task is active, if we remove the Guest Option from that task and migrated it, still it seems to be assigned to the Guest. Is it the expected behaviour?

**Comment by madhurrya** [comment] 2024-07-22 11:18
@burnettk @jasquat It'll be really nice when we show this 'not migratable' message, if we can show which task update(s) is/are preventing  the migration, as it becomes confusing sometimes why we can't migrate it. But not sure whether it's going to be practical if there are lot of changes in a model.


![Image](https://github.com/user-attachments/assets/19cd4e52-6662-47a1-a7a0-497551a0f271)

**Comment by madhurrya** [comment] 2024-07-22 12:30
Adding a note for later reference (as these are mentioned in different places)
In these scenarios we can't update and migrate an instance when that task is active.
1. Call activity (can't change properties of the call activity itself, but we can update the tasks inside it)
2. Sub process (can't change properties of the sub process itself, but we can update the tasks inside it)
3. Multi Instance tasks
4. Loop tasks
5. Signal boundary event - add/remove signals
6. When we loop back through a process which has already completed once

**Comment by jasquat** [comment] 2024-07-22 14:04
@madhurrya the guest task assignment seems like an issue and is an oversight. We do not recreate the HumanTask during migrations but we may need to either recreate or update more properties like assignment.

As far as the not migratable message goes, we are limited in what we information we have that will make sense to the user. We may be able to pull a little more info out of the diffs from spiff but uncertain it will make sense. Right now it hasn't been a requirement but it would be a nice to have.

**Comment by madhurrya** [comment] 2024-07-23 04:38
@burnettk @jasquat After an instance is completed we don't have a way to see the migration history of that. Do you think users will need this?

**Comment by madhurrya** [comment] 2024-07-23 04:58
Please check this issue 
https://github.com/sartography/spiff-arena/issues/1973

**Comment by madhurrya** [comment] 2024-07-23 05:35
@burnettk @jasquat noticed that in Samples site today some times it takes time to load the migration history table. Did anything change there which will take longer or is it just server performance?

![Image](https://github.com/user-attachments/assets/93d99c70-b995-439d-8952-35928d39d63e)

**Comment by burnettk** [comment] 2024-07-23 13:30
nah, i don't think anything changed in this regard recently. i'm inclined to ignore migration-related performance issues unless it's very annoying. if it works, i'm happy.

**Comment by madhurrya** [comment] 2024-07-24 15:16
@burnettk @jasquat @calexh-sar I think I have completed the migration testing.

It might be good to document (and inform the client) about these scenarios.
https://github.com/sartography/spiff-arena/issues/1671#issuecomment-2242841938

and about these known issues
https://github.com/sartography/spiff-arena/issues/1922
https://github.com/sartography/spiff-arena/issues/1973
(https://github.com/sartography/spiff-arena/issues/1974 - this one is just an edge case I think, not that important)

**Comment by burnettk** [comment] 2024-07-27 19:54
Incorporated these issues into the documentation as known issues and caveats, thank you.

**Closed** 2024-08-28 03:59 UTC
