### ISSUE TITLE
ProcessInstanceIsAlreadyLockedError

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#702] opened 2023-11-21 07:00 UTC
Our end-user noticed this error in prod yesterday when he was trying to submit his request (complete a user task).

![Image](https://github.com/sartography/spiff-arena/assets/104367255/796288f0-ab2d-4881-984b-79b24928278e)

**Comment by burnettk** [comment] 2023-11-21 13:13
many instances of this error will be resolved by #584

**Comment by danfunk** [comment] 2023-12-11 13:28
re-test after new background processor is in place.

**Comment by dinithihj** [comment] 2024-01-12 02:58
@burnettk @KB When you get a chance can you please have a look at the below error I mentioned earlier, I was not able to create instances with Cypress to test this issue due to the below error.

On dev.mod environment when a normal user creates a PP1/PP2 and clicks on the submit button below error is displayed.![image](https://github.com/sartography/spiff-arena/assets/123297840/f17f9111-7f35-41d4-84f9-31f5f6a4df96)

Video link - https://drive.google.com/file/d/1TsdwhCy2Pwk0gtcPrDuU-kkqFG7D6Hpf/view?usp=sharing

Note - Admin users can create requests without any issues.

**Comment by burnettk** [comment] 2024-01-17 14:52
the NotAuthorizedError was only affecting celery-enabled environments, and was confirmed resolved on dev.mod.

**Comment by dinithihj** [comment] 2024-01-18 04:06
This error did not occur during today's testing on dev.mod. I will continue to monitor it and report here if that occurs.

**Comment by madhurrya** [comment] 2024-02-13 08:11
Noticing the  'ProcessInstanceIsAlreadyLocked' error in dev.mod also. Created a new ticket for that https://github.com/sartography/spiff-arena/issues/1006. So I'll close this ticket as it'll be addressed in that ticket.

**Comment by burnettk** [comment] 2024-03-26 21:32
closing, as this is now tracked in #1006

**Closed by burnettk** 2024-03-26 21:32 UTC
Labels: bug
