### ISSUE TITLE
Displaying the progress info - interstitial page

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1061] opened 2024-02-19 11:12 UTC
There is an issue with displaying information on an interstitial page for looped processes. Despite multiple entries, it only shows the first value.

Example - CoinGecko report https://dev.app.spiff.status.im/process-models/misc:coingecko-reports
the interstitial page shows the value for the first coin instead of displaying info for each requested coin one by one.

**Comment by burnettk** [comment] 2024-02-19 15:20
here's a generic version of the process model xml that omits the service task. the problem is that the interstitial page UX always shows AAA instead of showing the subsequent elements in the list, like BBB and CCC, but not sure why yet. each task is operating correctly and has different task data as expected. the UI works correctly and shows different values when celery is enabled.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:spiffworkflow="http://spiffworkflow.org/bpmn/schema/1.0/core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="Definitions_96f6665" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.0.0-dev">
  <bpmn:process id="Process_cpoiqqn" name="Coin Rates" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1e2loqn</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_010l5xx">
      <bpmn:extensionElements>
        <spiffworkflow:instructionsForEndUser>All done</spiffworkflow:instructionsForEndUser>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0rgygmh</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1e2loqn" sourceRef="StartEvent_1" targetRef="Activity_1wytniy" />
    <bpmn:sequenceFlow id="Flow_17z0w3r" sourceRef="Activity_1wytniy" targetRef="Event_0da0nde" />
    <bpmn:scriptTask id="Activity_1wytniy" name="Set the list">
      <bpmn:incoming>Flow_1e2loqn</bpmn:incoming>
      <bpmn:outgoing>Flow_17z0w3r</bpmn:outgoing>
      <bpmn:script>coin_list = [
"AAA",
"BBB",
"CCC",
"DDD",
"EEE",
]

# Set List Count and Counter
coin_list_cnt = len(coin_list)
coin_list_loop_cnt = 0
</bpmn:script>
    </bpmn:scriptTask>
    <bpmn:exclusiveGateway id="Gateway_1w44m77">
      <bpmn:incoming>Flow_0ufmnpi</bpmn:incoming>
      <bpmn:incoming>Flow_0bszaj5</bpmn:incoming>
      <bpmn:outgoing>Flow_1mh1g7o</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_1mh1g7o" sourceRef="Gateway_1w44m77" targetRef="Activity_0c165tg" />
    <bpmn:exclusiveGateway id="Gateway_04a6dh6" name="Loop Count &#60; coin Count?" default="Flow_1hqlznn">
      <bpmn:incoming>Flow_03lljhp</bpmn:incoming>
      <bpmn:outgoing>Flow_0oubhpw</bpmn:outgoing>
      <bpmn:outgoing>Flow_1hqlznn</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_0oubhpw" sourceRef="Gateway_04a6dh6" targetRef="Event_07dw1go">
      <bpmn:conditionExpression>coin_list_loop_cnt == coin_list_cnt</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_1hqlznn" name="Yes" sourceRef="Gateway_04a6dh6" targetRef="Activity_11da4gr" />
    <bpmn:sequenceFlow id="Flow_03lljhp" sourceRef="Activity_0c165tg" targetRef="Gateway_04a6dh6" />
    <bpmn:intermediateThrowEvent id="Event_0da0nde" name="Rates REQUESTED">
      <bpmn:incoming>Flow_17z0w3r</bpmn:incoming>
      <bpmn:outgoing>Flow_0ufmnpi</bpmn:outgoing>
    </bpmn:intermediateThrowEvent>
    <bpmn:sequenceFlow id="Flow_0ufmnpi" sourceRef="Event_0da0nde" targetRef="Gateway_1w44m77" />
    <bpmn:intermediateThrowEvent id="Event_07dw1go" name="Current rates RECEIVED">
      <bpmn:incoming>Flow_0oubhpw</bpmn:incoming>
      <bpmn:outgoing>Flow_0rgygmh</bpmn:outgoing>
    </bpmn:intermediateThrowEvent>
    <bpmn:sequenceFlow id="Flow_0rgygmh" sourceRef="Event_07dw1go" targetRef="Event_010l5xx" />
    <bpmn:scriptTask id="Activity_11da4gr" name="Display the progress">
      <bpmn:extensionElements>
        <spiffworkflow:instructionsForEndUser>Got info for {{coin_symbol}} ({{coin_list_loop_cnt}} of {{coin_list_cnt}}).</spiffworkflow:instructionsForEndUser>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1hqlznn</bpmn:incoming>
      <bpmn:outgoing>Flow_0bszaj5</bpmn:outgoing>
      <bpmn:script>time.sleep(2)</bpmn:script>
    </bpmn:scriptTask>
    <bpmn:sequenceFlow id="Flow_0bszaj5" sourceRef="Activity_11da4gr" targetRef="Gateway_1w44m77" />
    <bpmn:scriptTask id="Activity_0c165tg" name="Get current rates">
      <bpmn:extensionElements>
        <spiffworkflow:preScript>coin_symbol = coin_list[coin_list_loop_cnt]</spiffworkflow:preScript>
        <spiffworkflow:postScript>coin_list_loop_cnt = coin_list_loop_cnt + 1


coin_symbol_cg.append(cg_symbol)
coin_symbol_cg_rates.append({"Coin Symbol": coin_symbol, "Coin Name": cg_name, "Conversion Rate": cg_usd_conversion_rate})</spiffworkflow:postScript>
        <spiffworkflow:instructionsForEndUser />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1mh1g7o</bpmn:incoming>
      <bpmn:outgoing>Flow_03lljhp</bpmn:outgoing>
      <bpmn:script>coin_symbol = coin_list[coin_list_loop_cnt]
coin_list_loop_cnt = coin_list_loop_cnt + 1</bpmn:script>
    </bpmn:scriptTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_cpoiqqn">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="12" y="192" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_010l5xx_di" bpmnElement="Event_010l5xx">
        <dc:Bounds x="792" y="192" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0sxkael_di" bpmnElement="Activity_1wytniy">
        <dc:Bounds x="90" y="170" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_1w44m77_di" bpmnElement="Gateway_1w44m77" isMarkerVisible="true">
        <dc:Bounds x="315" y="185" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_04a6dh6_di" bpmnElement="Gateway_04a6dh6" isMarkerVisible="true">
        <dc:Bounds x="615" y="185" width="50" height="50" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="607" y="242" width="67" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0da0nde_di" bpmnElement="Event_0da0nde">
        <dc:Bounds x="242" y="192" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="226" y="235" width="69" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_07dw1go_di" bpmnElement="Event_07dw1go">
        <dc:Bounds x="722" y="192" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="709" y="235" width="65" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0hc4fpr_di" bpmnElement="Activity_11da4gr">
        <dc:Bounds x="440" y="40" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0lqlgrn_di" bpmnElement="Activity_0c165tg">
        <dc:Bounds x="440" y="170" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1e2loqn_di" bpmnElement="Flow_1e2loqn">
        <di:waypoint x="48" y="210" />
        <di:waypoint x="90" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_17z0w3r_di" bpmnElement="Flow_17z0w3r">
        <di:waypoint x="190" y="210" />
        <di:waypoint x="242" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1mh1g7o_di" bpmnElement="Flow_1mh1g7o">
        <di:waypoint x="365" y="210" />
        <di:waypoint x="440" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0oubhpw_di" bpmnElement="Flow_0oubhpw">
        <di:waypoint x="665" y="210" />
        <di:waypoint x="722" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1hqlznn_di" bpmnElement="Flow_1hqlznn">
        <di:waypoint x="640" y="185" />
        <di:waypoint x="640" y="80" />
        <di:waypoint x="540" y="80" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="361" y="53" width="18" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_03lljhp_di" bpmnElement="Flow_03lljhp">
        <di:waypoint x="540" y="210" />
        <di:waypoint x="615" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ufmnpi_di" bpmnElement="Flow_0ufmnpi">
        <di:waypoint x="278" y="210" />
        <di:waypoint x="315" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0rgygmh_di" bpmnElement="Flow_0rgygmh">
        <di:waypoint x="758" y="210" />
        <di:waypoint x="792" y="210" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0bszaj5_di" bpmnElement="Flow_0bszaj5">
        <di:waypoint x="440" y="80" />
        <di:waypoint x="340" y="80" />
        <di:waypoint x="340" y="185" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by madhurrya** [comment] 2024-03-01 09:13
Tested with https://dev.app.spiff.status.im/process-models/misc:coingecko-reports and this issue seems to be fixed now.
![image](https://github.com/sartography/spiff-arena/assets/110527567/b8fadde4-81af-432e-b0b5-e3a6a965f75e)

@burnettk was this just a code side fix or did you update anything in the coingecko report model also related to this fix?

**Comment by jasquat** [comment] 2024-03-01 14:19
@madhurrya this was a code change only. No change to process models.

**Comment by madhurrya** [comment] 2024-03-12 03:51
Released to Prod on March 11th

**Closed by madhurrya** 2024-03-12 03:51 UTC
Labels: bug, help wanted, process
