### ISSUE TITLE
Process instance is stuck in a waiting state

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1177] opened 2024-03-07 14:12 UTC
There is a process that involves creating a purchase order for each cycle of a loop. The purchase order needs to be created 144 times, once for each active CC in the list. However, the process is currently stuck after creating the 140th purchase order and is in a "waiting" state.

The process model - https://dev.app.spiff.status.im/process-models/manage-procurement:procurement:purchase-orders-management:mass-creation-of-pos
Process instance example - https://dev.app.spiff.status.im/i/8231

things we think we should fix before this that may end up fixing this:
 * #773
 * #1190

**Comment by calexh-sar** [comment] 2024-03-07 18:42
@sashayar13 we discussed this post scrum today and suspect the problem is the background processor is interrupting the process after approximately three minutes and this normally would not be a problem except dev has so many open instances the cycle time is very long.  We are working on adding Celery to all instances so this issue will be addressed.  We do have a [intermittent bug](https://github.com/sartography/spiff-arena/issues/1006) that needs to be addressed to be sure Celery will run without issue.

Another solution, and likely the best way to approach this process even if Celery was running, would be to move all the elements inside a Parallel Multi-Instance Expanded Sub-Process.  This should make the overall process run faster and likely under the three minute threshold and so the background processor will not be a problem.  Madhurya indicated that there are 16 Test Cases around MI Sub-Processes you can review if you search with 'MI Sub Process'.  I also can assist or just convert if over if you would prefer.

**Comment by sashayar13** [comment] 2024-03-08 10:11
@calexh-sar can you please help me to configure this process? I tried to do it myself, but keep getting errors - https://dev.app.spiff.status.im/editor/process-models/manage-procurement:procurement:purchase-orders-management:mass-creation-of-pos/files/mass-creation-of-pos.bpmn

**Comment by calexh-sar** [comment] 2024-03-09 01:33
@sashayar13 the process is not completing when run with a handful of CC, but errors will attempting to run the full list.  The error is not definitive and seems to be related to one of the Service Tasks, but I will need to get with the devs on Monday to see get their insights.

To help with troubleshooting I disconnected the Data Objects and deleted the Data Outputs.  Would you please reconnect the Data Objects and add back the Data Outputs as needed and confirm the process still runs successfully.

**Comment by sashayar13** [comment] 2024-03-11 06:26
@calexh-sar Even with the deleted data associations and data outputs, the process still experiences the same error. https://dev.app.spiff.status.im/i/8558


![Image](https://github.com/sartography/spiff-arena/assets/104367255/0dcf2787-3ac4-4d34-ba2b-4538fe3b97fb)

**Comment by sashayar13** [comment] 2024-03-11 06:28
The "errored" instances are not set as "errored" but "running" 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/2d953de5-c25e-447b-9d86-ca87b18b9d20)

**Comment by harmeet-status** [comment] 2024-03-12 07:20
Another ticket which is related to the multi-instance subprocesses solution which was devised by @calexh-sar above: https://github.com/sartography/spiff-arena/issues/1190

**Comment by harmeet-status** [comment] 2024-03-12 07:22
Had a discussion with @sashayar13, this needs to be done either in Sprint 24 or Sprint 25 as we need this for Go-Live for Implicit 1st April.

**Comment by essweine** [comment] 2024-03-15 17:46
Additionally, this issue with the spiff library is also going to impact this process: https://github.com/sartography/SpiffWorkflow/issues/395

**Comment by calexh-sar** [comment] 2024-04-15 13:31
@madhurrya would you please retry after @sashayar13 give your the go ahead.

**Comment by madhurrya** [comment] 2024-04-17 10:28
I just checked my test model with 150 items and it completed this time without any error.
https://dev.app.spiff.status.im/process-models/misc:test:madhurya-testing:test-the-mass-po-creation-issue

Will test the real model when it's ready.

**Comment by calexh-sar** [comment] 2024-05-21 14:11
@sashayar13 pls let @madhurrya know when the real model is ready for testing.

**Comment by sashayar13** [comment] 2024-05-22 05:34
@MarD0607 is the one who is working on this process

**Comment by calexh-sar** [comment] 2024-05-22 10:53
@MarD0607 is the process model - https://dev.app.spiff.status.im/process-models/manage-procurement:procurement:purchase-orders-management:mass-creation-of-pos - ready for testing?

**Comment by MarD0607** [comment] 2024-05-22 11:08
@calexh-sar not yet

**Comment by danfunk** [comment] 2024-06-10 13:57
Elizabeth did some additional work on the core library that should have be released recently.   This is merged, and will get deployed to dev sometime today.  @dinithihj / @madhurrya - if you could please retest this ( Madhurya created a sample process model that is very similar to this use case that we can test.) and we can determine if it is ready for Marius to put back into place on the origial model.

**Comment by calexh-sar** [comment] 2024-06-18 01:39
@MarD0607 is the process model - https://dev.app.spiff.status.im/process-models/manage-procurement:procurement:purchase-orders-management:mass-creation-of-pos - ready for testing?

@dinithihj / @madhurrya  have you had a chance to test the sample process Dan referred to in the previous comment?

**Comment by madhurrya** [comment] 2024-06-18 02:44
@calexh-sar that code is not deployed to dev yet. I'll check that when it's deployed.

**Comment by MarD0607** [comment] 2024-06-18 10:35
@calexh-sar 
The process model is now ready for testing, and it has been adapted to work without the code changes for parallel MI

**Comment by madhurrya** [comment] 2024-07-01 11:29
So far I was not able to get these instances completed (these are with 1000 iterations). They are in the 'waiting' state. Might have to wait till the performance improvements are done related to MI subprocesses.
https://dev.app.spiff.status.im/process-models/misc:test:madhurya-testing:test-the-mass-po-creation-issue

![image](https://github.com/sartography/spiff-arena/assets/110527567/c97e4416-d978-4995-bdb5-2ca53e154cbd)

**Comment by madhurrya** [comment] 2024-08-21 12:54
Closing this issue, as the 'waiting' issue was mainly due to a large model that was running for hours. Hope the performance fixes will fix this type of issues in the future.

**Closed by madhurrya** 2024-08-21 12:54 UTC
Labels: help wanted, process
