### ISSUE TITLE
Get Supplier details from Iplicit

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1060] opened 2024-02-19 11:03 UTC
Get Supplier’s details (get by BBHR id of a core contributor - Supplier ID, Supplier Name, Tax Band, Currency) - need a process which can be used to get the details by using a CC’s BBHR

**Comment by sashayar13** [comment] 2024-02-19 11:03
1. I tested quickly a supplier creation/get details and it looks like:
    1. IntRef - is not written/can’t get it from the Iplicit
    2. Supplier code also is not registered
    3. the values for payment terms, tax bands are - tech id from Iplicit but not values we need

**Comment by calexh-sar** [comment] 2024-02-19 14:46
@sashayar13 @MarD0607 @harmeet-status am I correct in assuming that this issue should be prioritized as High since it is tagged for Sprint 22?

**Comment by sashayar13** [comment] 2024-02-19 14:50
yes, @calexh-sar , correct

**Comment by calexh-sar** [comment] 2024-02-26 15:06
@sashayar13 the supplier details can be viewer using the [Iplicit Maintain process. model](https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit).  I need additional insights into how the ContactAccount for CCs will be configured in Iplicit.  From the existing data that is in the sandbox instance, it appears that the `code` is not the BBHR API Id, so your request to 'get by BBHR id of a core contributor' may not be possible in the current configuration unless we download all the supplier information using the 'Search contact accounts' and then find the BBHR API Id and then extract the Iplicit "code" to then use the "Get a contact account details" endpoint to retrieve the details you want.

`"resp_iplicit_get": {
    "body": {
      "id": "8d23ded3-4fbe-47ef-a73a-00655127050e",
      "code": "HOL001",
      "hasNotes": false,
      "supplier": {
        "ext": {
          "BambooHR": "1316"
        },
        "currency": "EUR",
        "isActive": true,
        "accountId": "d3742eaf-962a-41b1-a995-6c178819a52d",
        "payTermId": "5f66776b-8156-4ffc-86bd-32658fd8004e",
        "taxBandId": "21c7fda8-3ae9-4d6d-aa10-ca7eae043136",
        "costCentreId": "0c30d545-6109-4c1e-b811-9449596e6be6",
        "departmentId": "f0d74369-a525-47ba-aee3-939dfb6edfdc",
        "taxBandFixed": false,
        "sendRemittance": true,
        "taxAuthorityId": "b2442d58-99ff-47e9-b33c-f7724f3a5e03",
        "costCentreFixed": false,
        "departmentFixed": false,
        "paymentMethodId": "1d9477d9-0f6d-489d-bf66-40490b42ceb3",
        "contactGroupSupplierId": "fb215a63-f625-44d2-8258-fcbd156e3390",
        "allowInvoiceDuplication": false,
        "applyDomesticReverseCharge": false
      },
      "createdBy": "galeas",
      "legacyRef": "HOL001(IFT)",
      "countryCode": "AD",
      "createdDate": "2024-02-05T16:10:52.167",
      "description": "HOLFREED SL",
      "lastModified": "2024-02-09T13:13:30.97",
      "hasAttachments": false,
      "lastModifiedBy": "Rachel"
    },
    "mimetype": "application/json",
    "http_status": 200,
    "operator_identifier": "http/GetRequestV2"
  }`

**Comment by MarD0607** [comment] 2024-03-02 20:56
@calexh-sar @sashayar13 For third party vendors see https://github.com/sartography/spiff-arena/issues/1148, we will generate the code in Spiff and send it to Iplicit, this will be stored in Iplicit through the POST call and then used for other calls when needed.

@calexh-sar The CC Iplicit Code is currently built using the same logic as for third party vendors ,see above issues.
For getting CC supplier details we may consider the following approach:
1. get from Iplicit a list of CC Code and BBHR ID
2. create a datastore with CC Iplicit Code and BBHR ID
3. when we start a process where we need to Get CC supplier card then:

- get from BBHR the BBHR ID ( by using the BBHR API ID we can retrieve probably the BBHR ID)
- check the mapping and retrieve the CC Code
- use the CC code in the GET call to Iplicit
I'm afraid that without a mapping logic stored in Spiff it will be difficult to navigate through the different IDs and codes.

**Comment by calexh-sar** [comment] 2024-03-07 03:06
Confirmed the BBHR Employee # can be stored in the Iplicit ContactAccount intRef and used to link the CCs in BBHR with those found in Iplicit in [dev Instance 7410](https://dev.app.spiff.status.im/process-instances/for-me/misc:service-tests:iplicit:maintain/7410).

**Comment by sashayar13** [comment] 2024-03-07 05:23
I'm waiting for a response from the Iplicit team about the PATCH/SEARCH calls

**Comment by sashayar13** [comment] 2024-03-08 09:07
@calexh-sar based on our discussion in Discord suggest we mark this ticket as "Completed"

**Comment by calexh-sar** [comment] 2024-03-08 11:43
Closing this ticket per this comment by @sashayar13 in Discord: I think we can close this ticket as "Completed" 🎉

**Closed by calexh-sar** 2024-03-08 11:43 UTC
Labels: process
