### ISSUE TITLE
File links not working

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#838] opened 2024-01-02 07:19 UTC
Cannot open file links created on PP1 task data. 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/7259b6ea-0bdd-4436-9a25-c18dd6c4184c)

**Comment by jasquat** [comment] 2024-01-02 19:44
This is probably caused by https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/routes/process_api_blueprint.py#L186 which was added when we were initially trying to add categories to data objects. I don't think it's needed for file download though.

**Comment by jbirddog** [comment] 2024-01-02 22:20
> This is probably caused by https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/routes/process_api_blueprint.py#L186 which was added when we were initially trying to add categories to data objects. I don't think it's needed for file download though.

Removing this param fixes the file download issue.

**Comment by jasquat** [comment] 2024-01-03 14:49
Fixed in #848

**Comment by dinithihj** [comment] 2024-01-09 03:50
Tested and verified on dev.app (Version - 319/321)
Now, files can be downloaded by clicking on the file link.

![image](https://github.com/sartography/spiff-arena/assets/123297840/1242120b-c54f-4639-b415-618e99f9c567)
![image](https://github.com/sartography/spiff-arena/assets/123297840/3fd2e89b-1492-443b-800f-7108a862072b)

**Comment by dinithihj** [comment] 2024-02-13 01:17
Released to prod on 2024 February 12

**Comment by madhurrya** [comment] 2024-08-21 04:27
This issue is already fixed.

**Closed by madhurrya** 2024-08-21 04:27 UTC
Labels: bug
