### ISSUE TITLE
Process recap page is not displayed

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1228] opened 2024-03-18 09:30 UTC
There is a process where the Process recap page (End Event Instructions) is not displayed.

Process Model - https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence
Process Instance sample - https://dev.app.spiff.status.im/i/838

**Comment by sashayar13** [comment] 2024-03-25 11:15
@calexh-sar, can you pls advise on when this item will be picked up by devs? I need to have it fixed ASAP - this is a dependency for the Expense processes go-live

**Comment by calexh-sar** [comment] 2024-03-25 12:37
@sashayar13 I would suspect that this would be done in the upcoming sprint.  If you want to guarantee that it does, I would suggest moving it to the top of the current Backlog items.

**Comment by jasquat** [comment] 2024-03-25 14:19
@calexh-sar Looks like it's returning an error when attempting to get the instructions. It's in the console as `Failed to complete an automated task. Error was: 'po_details' is undefined. Jinja2 template errors can happen when trying to display task data`

**Comment by sashayar13** [comment] 2024-03-25 16:28
@calexh-sar I thought it was at the top of the list. Updated the list again

**Comment by burnettk** [comment] 2024-03-25 21:01
@calexh-sar yes, it will say that it completed without error in this case, since the only issue was with the instructions, so we essentially just ignore the error.

**Comment by calexh-sar** [comment] 2024-03-25 23:36
@burnettk let me clarify a bit more.  When I looked at that instance this morning, it was showing Suspended and when I clicked on Events the last one contained the same error message @jasquat posted this morning.  And then this afternoon it was showing Compete and not error on the last event.  I guess there is a chance I inadvertently did a ForceRun on the instance, but don't think so.

**Comment by jasquat** [comment] 2024-03-26 15:12
Are you sure it was this instance that was marked as suspended? I'm not seeing anything in the events that would show an error. The last log was from the 18th.

**Comment by calexh-sar** [comment] 2024-03-26 15:48
@jasquat which instance where you looking at when you posted your comment about `'po_details' is undefined`?

**Comment by burnettk** [comment] 2024-03-26 16:02
@calexh-sar i think he ran a new instance with the browser developer tools console open, and it dumped out that error at the end.

**Comment by jasquat** [comment] 2024-03-26 18:25
@calexh-sar I was on instance 838. It shows the error in the developer console. https://dev.app.spiff.status.im/process-instances/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence/838

**Comment by calexh-sar** [comment] 2024-03-26 23:27
@sashayar13 can this error be reproduced using the current process.  PI #838 is outdated.

**Comment by sashayar13** [comment] 2024-03-27 05:35
@calexh-sar @jasquat @burnettk hello guys. Not sure what's been changed - but I've just run the process in the dev.app and the process recap page is displayed now https://dev.app.spiff.status.im/i/2754

**Comment by calexh-sar** [comment] 2024-03-27 12:07
@sashayar13 it appeared that in that version of the process the dictionary `po_details` was deleted before the End Event and therefore the Jinja code in the Instructions could not process the variables related to it.  Since it is working now, I am going to close this issue.

**Closed by calexh-sar** 2024-03-27 12:07 UTC
Labels: bug
