### ISSUE TITLE
Vendor data store - Errors

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1264] opened 2024-03-23 17:47 UTC
For the code check vs duplicates we still get errors, please see
https://dev.app.spiff.status.im/i/1979
https://dev.app.spiff.status.im/process-instances/for-me/manage-procurement:vendor-lifecycle-management:vendor-onboarding:create-request-for-vendor-onboarding/2031

**Comment by calexh-sar** [comment] 2024-03-27 00:19
@MarD0607 I believe the cause of the error is the corrupted data for duplicate vendor `STI002`, if I am assuming correctly that all vendors in the Vendor Data Store should have `contact` information.

![Image](https://github.com/sartography/spiff-arena/assets/54854669/38017260-009d-4d35-9a09-ab3821be72d9)

**Comment by calexh-sar** [comment] 2024-05-24 10:27
@MarD0607 is any additional work needed on this issue?

**Comment by MarD0607** [comment] 2024-05-27 07:49
@calexh-sar There could be one issue:
- are both fields, contact name and email, required for contact information or is it just 1 of them?
Some vendor data coming from Iplicit or from Request process may not have the full contact information.

**Comment by calexh-sar** [comment] 2024-05-28 10:46
@MarD0607 as far as the Data Store is concerned, it stores what you tell it to store and does not require anything.  The processes that will be looking for this data, i.e., contact name or email, may have a problem if it is not there.  Are there specific processes that are having an issue or are you trying to anticipate this potential issue?

**Comment by MarD0607** [comment] 2024-05-28 12:36
@calexh-sar Then it is ok to close this ticket since there are no restrictions on the data we can store in the Data Store.

**Comment by calexh-sar** [comment] 2024-05-28 12:42
Closing per @MarD0607's last comment.

**Closed by calexh-sar** 2024-05-28 12:42 UTC
Labels: bug
