### ISSUE TITLE
Cannot set DataSource of Data Store Reference within Collapsed Sub Process

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1058] opened 2024-02-19 06:03 UTC
Added a Data Store reference inside a Collapsed Sub Process. On the properties window, It was not possible to set the DataSource of Data Store Reference as it's getting reset. 

Sample process model - https://dev.app.spiff.status.im/editor/process-models/misc:qa:data-store-tests:access-data-store-within-collapsed-sub-process/files/access-data-store-within-collapsed-sub-process.bpmn

Video Link:- https://drive.google.com/file/d/14w12ZcdLdPcGW2JqURQ0YJoJkcn-iZIR/view?usp=sharing

![Image](https://github.com/sartography/spiff-arena/assets/123297840/ba6480ee-3f86-4a1f-8750-062217b85c67)

**Comment by calexh-sar** [comment] 2024-02-19 15:17
@madhurrya does linking the Data Store to the Sub-Process at the main process level work?

**Comment by dinithihj** [comment] 2024-02-19 20:01
@calexh-sar do you mean something like this? 
![image](https://github.com/sartography/spiff-arena/assets/123297840/02b18d3e-8956-49e0-ad10-88b082d52fab)

If so, that data store link can be set without an issue.

**Comment by dinithihj** [comment] 2024-02-19 20:31
Note - The same issue exists on data stores added within expanded subprocesses. 
Sample Process model -  https://dev.app.spiff.status.im/process-models/misc:qa:data-store-tests:access-data-store-within-expanded-sub-process
![image](https://github.com/sartography/spiff-arena/assets/123297840/a73f6058-f496-4e25-a640-820d92b59dc9)

**Comment by calexh-sar** [comment] 2024-02-20 12:22
@dinithihj thanks for the updates.  FWIW, I just recreated the Job Titles and Professional Levels Data Stores used in the Request New Role Process Model.  Both of these existing Data Stores are inside a second level Collapsed Sub-Process and worked as expected.  Mentioning this in case the issue is in the XML when a new Data Store is created and something @theaubmov needs to look into.

**Comment by madhurrya** [comment] 2024-08-21 05:23
This issue seems to be fixed now.

**Closed by madhurrya** 2024-08-21 05:23 UTC
Labels: bug
