### ISSUE TITLE
PI Migration - Call activity/Sub process update

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1907] opened 2024-07-12 07:16 UTC
While the PI is in a call activity like this, if we try to update the call activity (just change the task name) and migrate it, it gives the 'Process instance not migratable' message. I am not sure why. 
Same happens for a sub process also.
For other tasks we can update the task related info while it is active and migrate it. This happens only for a call activity/Sub process. 

Test model : https://timetracking.spiffworkflow.org/process-models/misc:qa:madhu-testing:call-activity-test-1

![Image](https://github.com/user-attachments/assets/6f742961-c125-4b74-b960-f39796136d62)

![Image](https://github.com/user-attachments/assets/aa5c1d16-cae6-492b-a0b6-2c011f650282)

![Image](https://github.com/user-attachments/assets/3c9fa6e4-f34e-4b24-8724-19858ce2881e)

**Comment by jasquat** [comment] 2024-07-12 13:26
I believe this is because tasks are completed within the call activity which technically come before the call activity and therefore would disallow migration: https://timetracking.spiffworkflow.org/process-instances/misc:qa:madhu-testing:call-activity-test-1/6206

@essweine does that sound right?

**Comment by madhurrya** [comment] 2024-07-12 13:54
@jasquat none of the tasks are completed within the call activity. I just updated the model as soon as the Call activity got active. 
![image](https://github.com/user-attachments/assets/74e086c0-8f97-4ed6-842c-8bf3fdc3921c)

**Comment by jasquat** [comment] 2024-07-12 17:13
The StartEvent is completed. That's enough to disallow migrations.

**Comment by jasquat** [comment] 2024-07-16 17:36
Closing this issue since it is as designed.

**Closed by jasquat** 2024-07-16 17:36 UTC
