### ISSUE TITLE
Update get_current_user in process models

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1436] opened 2024-04-23 12:03 UTC
Update get_current_user in existing process models to satisfy the changes needed for the background processor fixes.

**Comment by calexh-sar** [comment] 2024-04-23 18:42
@sashayar13 updates have been made to Good & Services, Travel and Expense in dev.

@madhurrya would you please test these to make sure that the processes still execute as intended and that the BO and SME can be changed by an Admin.

@burnettk are you showing any other processes that need to be updated on dev?

**Comment by burnettk** [comment] 2024-04-23 18:57
here's the full list after your updates:

```sh
 ~/projects/github/sartography/spiff-arena/spiffworkflow-backend | py 3.12.1 | main *13 | 4s > SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR=/Users/kevin/projects/github/status-im/process-models ./bin/run_local_python_script ./bin/lint_get_current_user_scripts.py
[2024-04-23 14:57:16,342] DEBUG in logging_service: Printing log to create app logger
\2024-04-23 14:57:16,343 - spiffworkflow_backend - DEBUG - SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR: /Users/kevin/projects/github/status-im/process-models
Found get_current_user() in script task remove_approver of file /Users/kevin/projects/github/status-im/process-models/misc/test/spiff-demo-testing/examples/1-basic-concepts/1-6-roles/lanes_with_dict.bpmn
Found get_current_user() in script task Activity_0tr6u2s of file /Users/kevin/projects/github/status-im/process-models/misc/test/spiff-demo-testing/examples/1-basic-concepts/1-6-roles/my_vacation.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/test/process-model-with-form-and-lane/lane_workflow_2023-02-06_14 57.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/test/process-model-with-form-and-lane/form_and_lane.bpmn
Found get_current_user() in script task Activity_04edrsy of file /Users/kevin/projects/github/status-im/process-models/misc/test/dinithi-testing/lane-test/lane-test.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/qa/test-lane/test-lane.bpmn
Found get_current_user() in script task set_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/show/on_form_submit.bpmn
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/show/on_load.bpmn
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/create/on_load.bpmn
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/all-users/user-preferences/on-load/on_load.bpmn
Found get_current_user() in script task SR-User_Info-Set_Defaults of file /Users/kevin/projects/github/status-im/process-models/misc/user-info/user-info.bpmn
Found get_current_user() in preScript of callActivity with id Activity_1u89kok in file misc/mvp-process/cc-invoice-approval-process-v2.bpmn
```

**Comment by calexh-sar** [comment] 2024-04-24 02:31
@madhurrya @dinithihj I updated the following processes that appear to be owned by QA, but did not test:

test - fixed but not tested
Found get_current_user() in script task remove_approver of file /Users/kevin/projects/github/status-im/process-models/misc/test/spiff-demo-testing/examples/1-basic-concepts/1-6-roles/lanes_with_dict.bpmn
Found get_current_user() in script task Activity_0tr6u2s of file /Users/kevin/projects/github/status-im/process-models/misc/test/spiff-demo-testing/examples/1-basic-concepts/1-6-roles/my_vacation.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/test/process-model-with-form-and-lane/lane_workflow_2023-02-06_14 57.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/test/process-model-with-form-and-lane/form_and_lane.bpmn
Found get_current_user() in script task Activity_04edrsy of file /Users/kevin/projects/github/status-im/process-models/misc/test/dinithi-testing/lane-test/lane-test.bpmn
Found get_current_user() in script task Activity_GetReviewers of file /Users/kevin/projects/github/status-im/process-models/misc/qa/test-lane/test-lane.bpmn

**Comment by calexh-sar** [comment] 2024-04-24 02:34
@burnettk I updated the processes listed in the previous comment and assume they will fall off your list.  The remaining processes listed below were not update because the were either no longer active to the best of my knowledge and likely should be deleted or were found in the extensions section that I don't feel I have the expertise to address:

not updaged since no longer used
Found get_current_user() in script task SR-User_Info-Set_Defaults of file /Users/kevin/projects/github/status-im/process-models/misc/user-info/user-info.bpmn
Found get_current_user() in preScript of callActivity with id Activity_1u89kok in file misc/mvp-process/cc-invoice-approval-process-v2.bpmn

Extensions
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/all-users/user-preferences/on-load/on_load.bpmn
Found get_current_user() in script task set_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/show/on_form_submit.bpmn
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/show/on_load.bpmn
Found get_current_user() in script task load_contact_preferences of file /Users/kevin/projects/github/status-im/process-models/misc/extensions/restricted/api-keys/create/on_load.bpmn

**Comment by madhurrya** [comment] 2024-04-24 04:39
Thanks for updating those QA models Alex.

@burnettk @calexh-sar we might have to update the demo site also.

**Comment by madhurrya** [comment] 2024-04-24 04:40
Alex, got this error when finance approving the manual upload expense process. Happens only in dev.app and it works in test.app. So should be related to this change.
https://dev.app.spiff.status.im/i/5411
![image](https://github.com/sartography/spiff-arena/assets/110527567/4b1438bd-8722-416e-a47b-59118a2fc010)

**Comment by calexh-sar** [comment] 2024-04-24 14:10
@madhurrya would you please retest the expense process.

**Comment by madhurrya** [comment] 2024-04-24 14:40
Noticed a similar/same error with PP2 also 
![image](https://github.com/sartography/spiff-arena/assets/110527567/4a2a7811-78e8-4a9f-9c44-79e21a412bd7)

I'll check the upload expense process

**Comment by madhurrya** [comment] 2024-04-24 15:20
Upload expense process error is fixed now.

**Comment by madhurrya** [comment] 2024-04-24 17:25
PP2 error seems to be fixed now.

**Comment by madhurrya** [comment] 2024-04-25 03:52
@calexh-sar were 'Upload expense evidence - procurement' and 'Upload expense evidence - travel' models were also updated or only the 'Upload expense evidence' process?

**Comment by calexh-sar** [comment] 2024-04-25 11:58
> [@calexh-sar](https://github.com/calexh-sar) were 'Upload expense evidence - procurement' and 'Upload expense evidence - travel' models were also updated or only the 'Upload expense evidence' process?

@madhurrya specifically regarding which Status processes (and not the QA/Test processes) were updated, the [budget_owner_approval](https://dev.app.spiff.status.im/editor/process-models/misc:approval-strategy-main:budget-owner-approval/files/budget_owner_approval.bpmn) and [smes_approval](https://dev.app.spiff.status.im/editor/process-models/misc:approval-strategy-main:sme-approval/files/smes_approval.bpmn) processes and these three processes called by them: [rgs_approval](https://dev.app.spiff.status.im/editor/process-models/manage-procurement:procurement:requisition-order-management:request-goods-services/files/rgs_approval.bpmn), [trvl_approval](https://dev.app.spiff.status.im/editor/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel/files/trvl_approval.bpmn) and [exp_approval](https://dev.app.spiff.status.im/editor/process-models/manage-finance:accounts-payable:process-expense-reports:expense-report-approval/files/exp_approval.bpmn).  

The top level processes listed when clicking the References button for the BO and SME approval processes seem to be the same and are:
```
[Process_1rpfnak](https://dev.app.spiff.status.im/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel-group-request) (manage-talents/manage-compensation-benefits-administer-payroll/business-related-meetingsevents/request-travel-group-request)
[Process_upload_expense_evidence_pur](https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-procurement) (manage-finance/accounts-payable/process-expense-reports/upload-expense-evidence-procurement)
[Process_upload_expense_evidence_travel_a58ngzd](https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-travel) (manage-finance/accounts-payable/process-expense-reports/upload-expense-evidence-travel)
[Request Goods or Services](https://dev.app.spiff.status.im/process-models/manage-procurement:procurement:requisition-order-management:request-goods-services) (manage-procurement/procurement/requisition-order-management/request-goods-services)
[Request Goods or Services](https://dev.app.spiff.status.im/process-models/misc:prototypes:edit-request:request-goods-or-services-edit-request) (misc/prototypes/edit-request/request-goods-or-services-edit-request)
[Request Travel](https://dev.app.spiff.status.im/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel) (manage-talents/manage-compensation-benefits-administer-payroll/business-related-meetingsevents/request-travel)
[Request Travel (temp)](https://dev.app.spiff.status.im/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel-with-option-for-changes-temp-model) (manage-talents/manage-compensation-benefits-administer-payroll/business-related-meetingsevents/request-travel-with-option-for-changes-temp-model)
[Request Travel (temp)](https://dev.app.spiff.status.im/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel-with-option-for-changes-temp-model) (manage-talents/manage-compensation-benefits-administer-payroll/business-related-meetingsevents/request-travel-with-option-for-changes-temp-model)
```
I would assume any of these top level processes that are used on prod need to be tested.  @sashayar13 would like to know if these changes are ready to push to prod.  Please advise if any additional testing is needed before I create the PRs.

**Comment by madhurrya** [comment] 2024-04-25 12:14
@calexh-sar Thanks for the details.

I tested these in dev.app
PP1, PP2, Upload expense 3 models. And PP1/PP2 BO and SME reassignment.

I guess the Create event - delete error I mentioned on Slack is not related to this.

Please let me know when these are merged to test.app, so I can do some more testing there before pushing to Prod.

**Comment by burnettk** [comment] 2024-04-25 14:00
i think old instances should continue to run using the model version they started with and so should be unaffected.

no, i don't think there is any code change required here.

**Comment by madhurrya** [comment] 2024-04-29 04:24
Tested the updates in test.app - PP1, PP2, Upload expense 3 models. And PP1/PP2 BO and SME reassignment. And couple of old instances and reassignments and didn't notice any issue.

**Comment by calexh-sar** [comment] 2024-04-30 11:36
@usama9500 checking to make sure that `get_current_user()` should only be used in the Pre-Script or Post-Script of a human task is in our documentation.

**Comment by madhurrya** [comment] 2024-05-10 14:21
Released to Prod.

**Closed by madhurrya** 2024-05-10 14:21 UTC
Labels: documentation, process
