### ISSUE TITLE
PP1/PP2 error when resuming after some admin features

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#888] opened 2024-01-11 09:45 UTC
Noticed an error when resuming the instance after performing the scenarios mentioned below. Please see the screenshots for details.

1. Admin approving on behalf of Budget owner
2. Admin approving on behalf of a SME
3. Skip Manual Task (Role - Infra, Manual Task - Update Application Landscape/Catalogue)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/cfce3557-81ec-499e-b7cd-a2628a3c4dc0)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/70e03e8d-c934-41a2-b2da-281e4ce9cdd8)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/51feae94-fb03-4c37-8f8e-14eead908741)

**Comment by harmeet-status** [comment] 2024-01-11 09:46
Comment from @madhurrya:

**Steps for Admin approving on behalf of Budget owner PP1**
1. Suspend the Process Instance
2. Open the Call Activity: "Get Approver(s) Review Outcome" ->"Get Budget Owner Review" -> "Do Approval Review"
3. Click on "Review the Request" (which is the current activity in Yellow) and select "Edit" in the pop up screen 
4. Change "review_outcome": "" to "review_outcome": "app"
5. If you want to add a comment, add a new line after the above line with the following variable name and comment.
"reviewer_comment": "Admin approved on behalf of Budget owner",
6. Click "Save" and then click "Execute Task"
7. "Resume" process instance.
8. Refresh the page after a few seconds and make sure the current activity is "Reminder: Check existing budget" (in Yellow)
9. Suspend the instance again
10. Click on "Reminder: Check existing budget" activity and click "Execute Task"
11. "Resume" process instance.
12. Refresh the page after a few seconds (now it takes about a minute) and make sure it has moved to the next activity as the current activity.
13. Now the rest of the process can flow.

**Steps for Admin approving on behalf of a SME  PP1**
1. Suspend the Process Instance
2. Open the relevant SME "Review the Request" activity (which is the current activity in yellow)
3. Click on "Review the Request" and select "Edit" in the pop up screen
4. Change "review_outcome": "" to "review_outcome": "app"
5. If you want to add a comment, add a new line after the above line with the following variable name and comment.
"reviewer_comment": "Admin approved on behalf of PPG",
6. Click "Save" and then click "Execute Task"
7. "Resume" process instance.
8. Refresh the page after a few seconds (now it takes about a minute) and make sure it has moved to the next activity as the current activity.
9. Now the rest of the process can flow.

**Comment by madhurrya** [comment] 2024-02-20 08:25
This issue is still there for both old and new instances

After the timer triggered
https://test.app.spiff.status.im/i/18912 (PP1 BO)
https://test.app.spiff.status.im/i/18911 (PP1 SME)

Before the timer triggered
https://test.app.spiff.status.im/i/19685  (PP1 BO)
https://test.app.spiff.status.im/i/19689 (PP1 SME)
https://test.app.spiff.status.im/i/19702  (PP2 SME)


Tried with this sample model and didn't get any error there
https://test.app.spiff.status.im/i/19701

And for PP2 BO also didn't get that error
https://test.app.spiff.status.im/i/19700 (PP2 BO)

May be something in the PP1 BO/SME and PP2 SME activity's script is causing this?

**Comment by madhurrya** [comment] 2024-03-11 09:17
I think this is a duplicate of https://github.com/sartography/spiff-arena/issues/686

**Comment by calexh-sar** [comment] 2024-06-10 10:31
@madhurrya would you please move whatever info/comments from this issue to #686 and close this one as a duplicate.

**Comment by madhurrya** [comment] 2024-06-10 11:04
Closing this as it is a duplicate.

**Closed by madhurrya** 2024-06-10 11:04 UTC
Labels: bug
