### ISSUE TITLE
UnicodeDecodeError errors for some users at login

### ISSUE THREAD

**Issue by jakubgs** [sartography/spiff-arena#600] opened 2023-10-31 09:23 UTC
Some users - including me - have seen this error when logging in using Keycloak:
```json
{
  "error_code":"internal_server_error",
  "message":"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 453: invalid continuation byte",
  "status_code":500,
  ...
}
```
This is caused by special Unicode characters in first or last name, for example:
```
keycloak=# SELECT email,first_name,last_name FROM user_entity WHERE username = 'example@status.im';
     email         | first_name | last_name 
-------------------+------------+-----------
 example@status.im | Aygün      | Ateş
(1 rows)
```

Initially I though this error is caused by Keycloak, since I found this disabled in Realm settings:

![image](https://github.com/sartography/spiff-arena/assets/2212681/f01aebce-d34b-4752-930a-0cafa0382450)

But even after adding the right locales to settings the error was not fixed:

![image](https://github.com/sartography/spiff-arena/assets/2212681/d13e8cc8-2e2c-4219-b617-61643c4b889d)

So my belief is that this is an issue with SpiffWorkflow itself.

**Comment by jakubgs** [comment] 2023-10-31 09:27
This appears to be a Python error, and Keycloak is written in Java, so that clearly indicates this is a SpiffWorkflow issue:

* https://wiki.python.org/moin/UnicodeDecodeError
* https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by jakubgs** [comment] 2023-10-31 09:40
I've made an example `badencoding@status.im` user in our test realm, and I can reproduce the error:
```json
{"error_code":"internal_server_error","message":"Error: Incorrect padding","error_line":"","error_type":"","file_name":"","line_number":0,"offset":0,"sentry_link":"https://sentry.io/sartography/spiffworkflow-backend/events/65f44b2801414c00acc45b99f3f20cd6","status_code":500,"tag":"","task_data":{},"task_id":"","task_name":"","task_trace":[],"response_headers":null,"response_message":null}
```

**Comment by burnettk** [comment] 2023-12-14 19:51
we can't reproduce this locally using the badencoding user that replicates on status envs, so that's annoying.

**Comment by jasquat** [comment] 2024-01-03 20:44
Fixed by #852

**Comment by burnettk** [comment] 2024-01-03 20:48
thanks for digging a bit more. we determined, from some random mailing list post, that we were incorrectly decoding the token payload. we swapped out the decode function and it seems to fix the issue.

**Comment by jakubgs** [comment] 2024-01-04 16:54
Oh very nice, thanks for fixing this.

**Comment by burnettk** [comment] 2024-01-04 22:08
fix is currently on dev.app

**Comment by jakubgs** [comment] 2024-01-05 14:34
I have logged into `dev.app` environment after re-adding the polish `ł` character into my surname and it works. Thanks!

**Closed** 2024-08-21 09:13 UTC
