### ISSUE TITLE
Messages - Updating a correlation property

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1812] opened 2024-06-25 07:39 UTC
In the Send task I had the correlation property set like this

![Image](https://github.com/sartography/spiff-arena/assets/110527567/dc4aa648-6a02-491d-9720-44a373d5f495)

I changed it from name to age like this

![Image](https://github.com/sartography/spiff-arena/assets/110527567/509987ca-370c-4839-83e8-cc3d82497cc3)

Now when I go to the Receive task which uses the same Message, I see both these properties here

![Image](https://github.com/sartography/spiff-arena/assets/110527567/3b84f724-b663-4c43-9288-123524305330)

[unit-test-send-task-new (4).bpmn.txt](https://github.com/user-attachments/files/15966788/unit-test-send-task-new.4.bpmn.txt)
[unit-test-receive-task-new (4).bpmn.txt](https://github.com/user-attachments/files/15966787/unit-test-receive-task-new.4.bpmn.txt)

**Comment by theaubmov** [comment] 2024-06-25 09:16
I think this is the expected behavior which is that when you change message correlation properties on the sender and then return to the receiver, you should see the newly added properties as well as the old ones, since they are still present in the XML with a notification message that says "you need to save again to confirm the new message configuration". and at this moment the user can confirm deleting old properties and save the message config, 

This is helpful for providing users with full visibility into what's in the XML and process group, but I agree it can be confusing. 

We can create a new ticket for the upcoming release to improve the UX of the message editor and resolve this potential confusion. But for the current release, this behavior is expected.

**Comment by madhurrya** [comment] 2024-06-25 09:55
But I am not sure whether this generic message will give the user a proper idea 
![image](https://github.com/sartography/spiff-arena/assets/110527567/c7057076-cd52-40c2-a58a-aa5d4227e49b)

I understand it from the implementation side. But from a general user's perspective he might be confused when he see both these properties there.

Actually what I understood and thought and expected after reading that message  (" Updating the message properties by saving is recommended to ensure data consistency") was if I save it then it'll get automatically updated it to be consistent with what I did in the Send task.

**Comment by burnettk** [comment] 2024-06-27 15:07
This is the along the same lines as #1810  and #1808 . Closing for the same reason.

**Closed by burnettk** 2024-06-27 15:07 UTC
